version: "3.3"

services:
  app:
    image: app:latest
    build: .
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      - NODE_ENV=dev
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=${IPV4}
    volumes:
      - ./:/app/
    env_file:
      - .env.local